get deno installer working

diff --git a/wildflower-local b/wildflower-local
--- a/wildflower-local
+++ b/wildflower-local
@@ -8,7 +8,20 @@ script_root=$(dirname ${x#*n})
 if [ ! -s "$DENO_INSTALL" ]; then
   # Deno require a manual step (adding to the PATH), so we can't do other commands until the user has done that. :/ 
   # I mean, we could try to guess at the deno install, but I'd rather not. At least for now
-  curl -fsSL https://deno.land/install.sh | sh
+  echo "Deno not found! Attempting install..."
+
+  curl -fsSL https://deno.land/install.sh | sh || {
+    echo
+    echo "No permission install failed. Provide password for sudo install (or install it manually yourself.)"
+
+    # Not sure we want this part?
+    curl -fsSL https://deno.land/install.sh | sudo -u $USER sh || {
+      echo
+      echo "Could not install Deno."
+      echo "Either re-run to try again, or install Deno manually:"
+      echo "  https://docs.deno.com/runtime/manual/getting_started/installation"
+    }
+  }
 else
   if [ "$1" = "gather" ]; then
     deno run --allow-read --allow-write --allow-env $script_root/gather.js
